<?xml version="1.0" encoding="utf-8"?><Database Name="TempHum" Class="TempHumDataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\TempHum.mdf;Integrated Security=True" SettingsObjectName="Home_automation.Properties.Settings" SettingsPropertyName="TempHumConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Day" Member="Days">
    <Type Name="Day">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Temperature" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Humidity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>